datasource:
  driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  # url: jdbc:mysql://139.159.221.252:3306/yblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
  # username: root
  # password: '!Xx19711021'
  url: jdbc:p6spy:mysql://localhost:3306/questionnaire?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
  username: root
  password: '123456'

